version: 2
jobs:
  build:

    working_directory: ~/circleci-geogson

    docker:
      - image: circleci/openjdk:8-jdk-browsers

    context: org-global

    steps:

      - checkout

      - restore_cache:
          key: circleci-geogson-{{ checksum "pom.xml" }}

      - run: mvn package

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-geogson-{{ checksum "pom.xml" }}

      - store_test_results:
          path: target/surefire-reports

      - deploy:
          name: Release master
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./build/deploy.sh
            fi